name: Build & Deploy to cPanel (FTP)

on:
  push:
    branches: [ "main" ]  # cambia si usas otra rama
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test
        continue-on-error: true  # Continúa aunque fallen los tests

      - name: Build check
        run: npm run build

  deploy:
    needs: test  # 👈 Solo deploy si los tests pasan
    runs-on: ubuntu-latest
    environment: auroracpanel   # 👈 esto es clave
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install deps (dev)
        run: npm ci

      - name: Build (TypeScript -> dist/)
        run: npm run build

      # Preparo carpeta deploy/ con lo necesario para producción
      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -r dist deploy/
          cp -r public deploy/
          cp -r locales deploy/
          cp package.json package-lock.json deploy/
          cp .env.example deploy/.env

      # No instalar node_modules aquí - se instalarán en el servidor
      # En cPanel, ejecutar: npm install --production

      # Opcional: si usas Passenger/Node en cPanel y tu entrypoint es app.js en dist/
      - name: Add .htaccess for Passenger
        run: |
          cat > deploy/.htaccess <<'EOF'
          PassengerEnabled on
          PassengerAppEnv production
          PassengerAppRoot .
          PassengerStartupFile dist/app.js
          EOF

      # Nota: Para ejecutar migraciones en cPanel, ejecutar manualmente:
      # npm run migrate-prod

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: deploy/
          server-dir: ${{ secrets.FTP_SERVER_DIR || '/public_html/' }}
          exclude: |
            **/.git*
            **/.github*
            **/.DS_Store
            **/node_modules/**
            **/.env
            **/src/**
            **/tsconfig.json
            **/.eslintrc.json
            **/jest.config.js
            **/nodemon.json